### ISSUE TITLE
No module named 'TB2J_OpenMX.cmod._scfout_parser'

### ISSUE THREAD

**Issue by Secondlalala** [mailhexu/TB2J-OpenMX#1]
Dear hexu
  Your code of TB2J is quite helpful, i am using it to calculate the exchange parameters. However, i find there is an error when i run the code. 
![image](https://user-images.githubusercontent.com/44155131/100614307-e78b5300-3350-11eb-8921-4174e9efd773.png)
  Could you please give me some advise to fix this problem?
Regards.
Wenqiang Xie

**Comment by mailhexu** [comment]
Hi,
 Sorry for the late reply. 
 It seems the installation was not successful. Could you reinstall TB2J_OpenMX using 
pip install TB2J_OpenMX --upgrade
