### ISSUE TITLE
Exchange parameters obtained from TB2J-openmx does not accord with crystal symmetries.

### ISSUE THREAD

**Issue by jerene** [mailhexu/TB2J-OpenMX#3]
Recently, I tried to extract exchange parameters in monolayer CrI3, and found that although input crystal structure has three-fold rotational symmetry along z axis, but exchange parameters cannot keep this symmetry in TB2J results.

**Comment by mailhexu** [comment]
Hi, 
Sorry for the late reply. How large are the differences between the values? Could you send the input files? Thanks!
HeXu

**Comment by mailhexu** [comment]
Hi, 
A recent update to version 0.5.0 made a big improvement on the numerical accuracy. Not sure this is related to the problem but perhpas you can try. 
Best wishes,
HeXu

**Comment by jerene** [comment]
Hi He,

Thanks a lot. I will try it soon.
Best,
Jiaheng



***@***.***
 
From: Xu He
Date: 2023-10-05 16:58
To: mailhexu/TB2J-OpenMX
CC: jerene; Author
Subject: Re: [mailhexu/TB2J-OpenMX] Exchange parameters obtained from TB2J-openmx does not accord with crystal symmetries. (Issue #3)
Hi,
A recent update to version 0.5.0 made a big improvement on the numerical accuracy. Not sure this is related to the problem but perhpas you can try.
Best wishes,
HeXu
